-- =========================================================================
-- VANGUARD MOTORS - SUPABASE SCHEMA SETUP
-- Paste this script directly inside the Supabase SQL Editor to build tables.
-- =========================================================================

-- 1. Create the Vehicles/Cars table
CREATE TABLE IF NOT EXISTS vehicles (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  make text NOT NULL,
  model text NOT NULL,
  year integer NOT NULL,
  price numeric(12, 2) NOT NULL,            -- Stored as numeric for comparison/sorting (e.g. 68000.00)
  mileage integer NOT NULL,                 -- Stored as integer for range queries (e.g. 12400)
  body_type text NOT NULL,                  -- e.g. 'Coupe', 'SUV', 'Sedan'
  color text,                               -- e.g. 'Guards Red'
  location text,                            -- Showroom depot location
  status text NOT NULL DEFAULT 'available' CHECK (status IN ('available', 'reserved', 'sold')),
  date_added timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
  specs text[] DEFAULT '{}'::text[] NOT NULL, -- String array for vehicle packages
  condition_notes text,
  thumbnail_image text,                     -- URL to primary search image
  images text[] DEFAULT '{}'::text[] NOT NULL -- String array for secondary slide images
);

-- Enable Row Level Security (RLS) on vehicles table
ALTER TABLE vehicles ENABLE ROW LEVEL SECURITY;

-- 2. Define access policies
-- Policy: Allow everyone (anonymous/public) to read vehicle catalog listings
CREATE POLICY "Allow public read access" ON vehicles
  FOR SELECT TO public USING (true);

-- Policy: Allow authenticated agents and admin operators full CRUD access
CREATE POLICY "Allow agent/admin full access" ON vehicles
  FOR ALL TO authenticated USING (true);
